import Foundation
import SwiftData

/// One-time pass that rewrites the most recent weekly digest and monthly report when they were
/// written by the pre-grammar Gemma path (3.0.4 and earlier), which could invent details.
/// 3.0.5's grammar only protects what is generated from then on; a digest or report whose
/// period has already ended is never regenerated by the normal 24h rule, so it would stay as it
/// is. Latest period only (decided 2026-09-27): older ones are left alone.
///
/// Non-destructive, like `UngroundedInsightCleanup`: it inserts a newer row for the same period
/// rather than deleting or editing the old one, so CloudKit has no tombstone to hand out and
/// "newest wins" in every reader. Foundation Models output is never touched.
enum PreGrammarInsightRegrade {
    static let flag = "mirror.didRegradePreGrammarInsights.v1"
    private static let attemptsKey = "mirror.regradeAttempts.v1"
    /// Runs that reached generation without finishing (cancelled, failed, or only a fallback
    /// came back). After this many the pass gives up instead of retrying every foreground.
    private static let maxAttempts = 3

    /// The latest row of each type that the pre-grammar path may have written: Gemma only. A row
    /// with no engine predates attribution (2026-09-04), when Foundation Models (since 2026-08-16)
    /// may have written it, and its output is never touched (backlog A15b). Such a row is also
    /// over a month old, so leaving it costs little.
    static func candidates(among insights: [Insight]) -> [Insight] {
        [InsightType.weeklyDigest, .monthlyReport].compactMap { type in
            guard let latest = insights.filter({ $0.type == type }).max(by: { $0.generatedAt < $1.generatedAt }),
                  latest.generatedByEngine == LLMEngine.gemma.rawValue,
                  !InsightService.isGrammarGrounded(latest.content)
            else { return nil }
            return latest
        }
    }

    @MainActor
    static func runIfNeeded(context: ModelContext) async {
        let defaults = UserDefaults.standard
        guard !defaults.bool(forKey: flag) else { return }
        guard MirrorEncryption.canEncrypt(creatingIfNeeded: false) else { return }  // writes encrypted rows; retry next activation
        // Same wait-for-CloudKit deferral as UngroundedInsightCleanup: a store that hasn't
        // finished syncing could look like it has nothing (or the wrong latest row).
        guard defaults.integer(forKey: UngroundedInsightCleanup.backgroundingCountKey) >= 1 else { return }

        let insights = (try? context.fetch(FetchDescriptor<Insight>())) ?? []
        let entries = ((try? context.fetch(FetchDescriptor<Entry>(sortBy: [SortDescriptor(\.createdAt, order: .reverse)]))) ?? [])
            .filter(InsightService.hasReadableContext)
        guard !insights.isEmpty, !entries.isEmpty else { return }

        let todo = candidates(among: insights)
        guard !todo.isEmpty else {
            defaults.set(true, forKey: flag)
            return
        }
        guard mirrorApp.modelAvailable() else { return }
        let attempts = defaults.integer(forKey: attemptsKey)
        if attempts >= maxAttempts {
            defaults.set(true, forKey: flag)
            return
        }
        defaults.set(attempts + 1, forKey: attemptsKey)

        var allDone = true
        for old in todo {
            let period = old.periodIdentifier
            // The normal runners' keys, so this can't generate the same period at the same time.
            let key = old.type == .weeklyDigest ? "digest_\(period)" : "monthlyReport_\(period)"
            guard InsightGenerationCoordinator.shared.claim(key: key) else { allDone = false; continue }
            defer { InsightGenerationCoordinator.shared.release(key: key) }
            do {
                switch old.type {
                case .weeklyDigest:
                    let week = entries.filter {
                        DateHelpers.digestWeekIdentifier(for: $0.createdAt) == period
                            || DateHelpers.weekIdentifier(for: $0.createdAt) == period
                    }
                    guard week.count >= InsightService.weeklyDigestMinimumWeekEntries else { continue }
                    let (text, engine) = try await InsightService.generateWeeklyDigest(weekEntries: week, allEntries: entries)
                    // A "couldn't confirm" card must not replace what's there; try again later.
                    guard !InsightService.isUngroundedFallback(text) else { allDone = false; continue }
                    context.insert(Insight(type: .weeklyDigest, content: text, periodIdentifier: period, generatedByEngine: engine))
                case .monthlyReport:
                    let month = entries.filter { DateHelpers.monthIdentifier(for: $0.createdAt) == period }
                    guard month.count >= InsightService.monthlyReportMinimumEntries else { continue }
                    let (text, engine) = try await InsightService.generateMonthlyReport(monthEntries: month, allEntries: entries)
                    guard !InsightService.isUngroundedFallback(text) else { allDone = false; continue }
                    context.insert(Insight(type: .monthlyReport, content: text, periodIdentifier: period, generatedByEngine: engine))
                default:
                    continue
                }
                try context.save()
            } catch {
                allDone = false  // cancelled or failed: retry on a later foreground
            }
        }

        WidgetBridge.syncWeeklyDigest(from: context)
        WidgetBridge.syncMonthlyReport(from: context)
        if allDone { defaults.set(true, forKey: flag) }
    }
}
