import Foundation
import SwiftData

/// One-time pass that rewrites the most recent weekly digest and monthly report when they were
/// written by the pre-grammar Gemma path (3.0.4 and earlier), which could invent details.
/// 3.0.5's grammar only protects what is generated from then on; a digest or report whose
/// period has already ended is never regenerated by the normal 24h rule, so it would stay as it
/// is. Latest period only (decided 2026-09-27): older ones are left alone.
///
/// Non-destructive, like `UngroundedInsightCleanup`: it inserts a newer row for the same period
/// rather than deleting or editing the old one, so CloudKit has no tombstone to hand out and
/// "newest wins" in every reader. Foundation Models output is never touched.
enum PreGrammarInsightRegrade {
    static let flag = "mirror.didRegradePreGrammarInsights.v1"

    /// The latest row of each type that the pre-grammar path may have written.
    static func candidates(among insights: [Insight]) -> [Insight] {
        [InsightType.weeklyDigest, .monthlyReport].compactMap { type in
            guard let latest = insights.filter({ $0.type == type }).max(by: { $0.generatedAt < $1.generatedAt }),
                  latest.generatedByEngine != LLMEngine.foundationModels.rawValue,
                  !InsightService.isGrammarGrounded(latest.content)
            else { return nil }
            return latest
        }
    }

    @MainActor
    static func runIfNeeded(context: ModelContext) async {
        let defaults = UserDefaults.standard
        guard !defaults.bool(forKey: flag) else { return }
        // Same wait-for-CloudKit deferral as UngroundedInsightCleanup: a store that hasn't
        // finished syncing could look like it has nothing (or the wrong latest row).
        guard defaults.integer(forKey: UngroundedInsightCleanup.backgroundingCountKey) >= 1 else { return }

        let insights = (try? context.fetch(FetchDescriptor<Insight>())) ?? []
        let entries = ((try? context.fetch(FetchDescriptor<Entry>(sortBy: [SortDescriptor(\.createdAt, order: .reverse)]))) ?? [])
            .filter(InsightService.hasReadableContext)
        guard !insights.isEmpty, !entries.isEmpty else { return }

        let todo = candidates(among: insights)
        guard !todo.isEmpty else {
            defaults.set(true, forKey: flag)
            return
        }
        guard mirrorApp.modelAvailable() else { return }

        var allDone = true
        for old in todo {
            let period = old.periodIdentifier
            let key = "regrade_\(old.type.rawValue)_\(period)"
            guard InsightGenerationCoordinator.shared.claim(key: key) else { allDone = false; continue }
            defer { InsightGenerationCoordinator.shared.release(key: key) }
            do {
                switch old.type {
                case .weeklyDigest:
                    let week = entries.filter {
                        DateHelpers.digestWeekIdentifier(for: $0.createdAt) == period
                            || DateHelpers.weekIdentifier(for: $0.createdAt) == period
                    }
                    guard week.count >= InsightService.weeklyDigestMinimumWeekEntries else { continue }
                    let (text, engine) = try await InsightService.generateWeeklyDigest(weekEntries: week, allEntries: entries)
                    context.insert(Insight(type: .weeklyDigest, content: text, periodIdentifier: period, generatedByEngine: engine))
                case .monthlyReport:
                    let month = entries.filter { DateHelpers.monthIdentifier(for: $0.createdAt) == period }
                    guard month.count >= InsightService.monthlyReportMinimumEntries else { continue }
                    let (text, engine) = try await InsightService.generateMonthlyReport(monthEntries: month, allEntries: entries)
                    context.insert(Insight(type: .monthlyReport, content: text, periodIdentifier: period, generatedByEngine: engine))
                default:
                    continue
                }
                try context.save()
            } catch {
                allDone = false  // cancelled or failed: retry on a later foreground
            }
        }

        WidgetBridge.syncWeeklyDigest(from: context)
        WidgetBridge.syncMonthlyReport(from: context)
        if allDone { defaults.set(true, forKey: flag) }
    }
}
